### ISSUE TITLE
[Bug]: Jarvide responds to its own message/any other bot's messages

### ISSUE THREAD

**Issue by unmoo1707** [CaedenPH/Jarvide#106]
### What happened?

A bug happened!
I ran the command `jarvide roast @jarvide`
so when it sends the embed, it mentions itself, which triggers the jarvide welcome embed
I also tried to get a bot to ping jarvide, and it responded.

### Version

Latest

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct & Terms of service

**Comment by sifte** [comment]
I'm pretty sure this is fixed already [here](https://github.com/CaedenPH/Jarvide/blob/main/src/bot.py#L75-L76)
