### ISSUE TITLE
[Bug]: links and calculator

### ISSUE THREAD

**Issue by realstealthninja** [CaedenPH/Jarvide#110]
### What happened?

# hello developers and caeden
> this issue has been affecitng me for a while and its annoying as fuck i cant deal with it. it ruins the flow of every gif or link i send
### detailed
  so when the bot sees a link which has a -randomnumber in it it just messages the channel with the calculation embed
  its kinda annoying since it ruins the moment. as for how to fix it DO IT YOURSELF YOU LAZY ASSES

### Version

Latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct & Terms of service

**Comment by Dekriel** [comment]
I think the people who are making the calculator are working on it. It's still in production. "Jarvide removeconfig" is also in development.

**Comment by realstealthninja** [comment]
tried it didnt work innit bruv?

**Comment by Dekriel** [comment]
As I said, it's still in development.

**Comment by realstealthninja** [comment]
i understand innit bruv

**Comment by realstealthninja** [comment]
this shouldnt be a major priority but a quality of life thing

**Comment by realstealthninja** [comment]
actually ill try to fix it if thats the one thing i know how to do

**Comment by Dekriel** [comment]
alrighty then

**Comment by NotFlameDev** [comment]
This issue was fixed in https://github.com/CaedenPH/Jarvide/pull/104.
