### ISSUE TITLE
Hierarchy check for permission related commands (e.x role cmd)

### ISSUE THREAD

**Issue by Pandabweer** [CaedenPH/Jarvide#74]
**Describe the bug**

**To Reproduce**
Try to give yourself the same, highest role as the bot.

**Expected behavior**
A message saying the bots has not enough perms using the error handler of disnake.py

**Additional context**
The user also would not be able to give him/herself a higher role than he/she currently has.

**Comment by sarthak-py** [comment]
https://github.com/CaedenPH/Jarvide/commit/a3f74bae1a04ee81b15f6c243c208b7c6d8d70b6 already implemented ;)

**Comment by Pandabweer** [comment]
My fault for leaving it too broad.
Editing...

**Comment by kaylebetter** [comment]
closing this since #70 fixes this issue
